Configuring for pure-python
zopefoundation/zope.datetime pull request #19
Opened 2023-04-09 15:32 UTC by gforcada

2023-04-09 15:34 UTC, gforcada commented
@icemac I'm no admin in the `zopefoundation` organization nor on this repository, so I can not remove the `py27` check that is marked as required, would you mind doing that? 🍀 🙇🏾

2023-04-10 13:55 UTC, dataflake commented
Did you create the PR with the script `drop-legacy-python.py` in meta/config? That also adds a change log entry and guides you what else to look for.

2023-04-11 06:09 UTC, icemac commented
> Did you create the PR with the script `drop-legacy-python.py` in meta/config? That also adds a change log entry and guides you what else to look for.

Additionally this script asks you to remove `six` and runs `pyupgrade`, so I'd prefer a PR using this script.

2023-04-11 22:14 UTC, gforcada commented
I was not aware of that script, let me put this one on draft then and use that instead. Probably tomorrow 😴

2023-04-15 07:37 UTC, gforcada commented
I did run `drop-legacy-python.py` and fixed the `tox -e lint` errors.

Let me know if you want more changes to be made 😄

2023-04-15 08:05 UTC, dataflake requested changes
Just a few small items that are not automated

2023-04-15 08:05 UTC, dataflake commented on setup.py
Please change `author_email` to zope-dev@zope.dev and add `python_requires='>=3.7'`. Those are non-automated changes that we always do manually where needed.

2023-04-15 08:54 UTC, gforcada commented on setup.py
Thanks, did that and dropped `six` from `install_requires` as well 😄

2023-04-15 09:56 UTC, dataflake approved these changes

2023-04-15 09:56 UTC, dataflake commented
You don't need to manually re-request a review, I get email for all changes as an active reviewer, anyway, and will look at them when I have a moment.

2023-04-15 13:51 UTC, merged